import {ArrowRight,Check,ChevronDown,ChevronLeft,ChevronRight,Cuboid,Heart,Play,ShieldCheck,Sparkles,Stethoscope} from 'lucide-react';
import './mimi-landing.css';

type Props={onNavigate:(path:'/login'|'/signup')=>void;onDemo:()=>void};
const systems=[['Heart','/study/anatomy/heart/organ.webp'],['Brain','/study/anatomy/brain/organ.webp'],['Lungs','/study/anatomy/lungs/organ.webp'],['Liver','/study/anatomy/liver/organ.webp'],['Kidneys','/study/anatomy/kidneys/organ.webp'],['Eyes','/study/anatomy/eyeball/organ.webp'],['Skin','/study/anatomy/skin/organ.webp'],['Pancreas','/study/anatomy/pancreas/organ.webp'],['Intestines','/study/anatomy/intestine/organ.webp']];
const footerColumns=[['Explore','Learning paths','3D atlas','Practice lab','Study sets','Daily challenge'],['About Mimi','Our approach','For educators','Accessibility','Research','Careers'],['Support','Help center','Contact us','Community guidelines','Status'],['Legal','Privacy','Terms','Data policy','Cookie policy']];
function Logo(){return <span className="market-logo"><i>m</i>Mimi</span>}
function Button({children,onClick,kind='primary'}:{children:React.ReactNode;onClick:()=>void;kind?:'primary'|'outline'|'white'}){return <button className={`market-button ${kind}`} onClick={onClick}>{children}</button>}

export default function MimiLanding({onNavigate,onDemo}:Props){
 const scrollSystems=(direction:number)=>document.querySelector('.market-system-list')?.scrollBy({left:direction*300,behavior:'smooth'});
 return <main className="mimi-market">
  <nav className="market-nav"><button className="market-brand-button" onClick={()=>scrollTo({top:0,behavior:'smooth'})}><Logo/></button><div className="market-nav-actions"><button className="market-language">ANATOMY FOR EVERYONE <ChevronDown size={15}/></button><Button kind="outline" onClick={()=>onNavigate('/login')}>Log in</Button></div></nav>
  <section className="market-hero"><div className="market-hero-art"><span className="hero-orbit orbit-one"/><span className="hero-orbit orbit-two"/><img src="/mimi/mascots/mimi-welcome.png" alt="Mimi, the anatomy learning companion"/><span className="hero-chip chip-heart"><Heart size={17} fill="currentColor"/> HEART</span><span className="hero-chip chip-cube"><Cuboid size={17}/> 3D</span></div><div className="market-hero-copy"><p className="market-kicker"><Sparkles size={16}/> INTERACTIVE HUMAN ANATOMY</p><h1>See the body. <em>Understand</em> it.</h1><p>Explore human anatomy through short, memorable lessons, real 3D structures, and challenges that make every detail click.</p><div className="market-hero-ctas"><Button onClick={()=>onNavigate('/signup')}>Start learning <ArrowRight size={18}/></Button><Button kind="outline" onClick={()=>onNavigate('/login')}>I already have an account</Button></div></div></section>
  <section className="market-system-nav" aria-label="Explore body systems"><button aria-label="Previous systems" onClick={()=>scrollSystems(-1)}><ChevronLeft/></button><div className="market-system-list">{systems.map(([name,image])=><button key={name}><img src={image} alt=""/><span>{name}</span></button>)}</div><button aria-label="Next systems" onClick={()=>scrollSystems(1)}><ChevronRight/></button></section>
  <section className="market-split market-effective"><div><p className="market-kicker green"><Check size={16}/> LEARN BY DOING</p><h2>clear. curious. connected.</h2><p>Mimi makes complex anatomy feel approachable. Rotate structures, spot relationships, and work through lessons that build toward clinical understanding—not just memorisation.</p><button className="market-inline" onClick={()=>onNavigate('/signup')}>Build your anatomy map <ArrowRight size={18}/></button></div><div className="market-art-card"><img src="/study/anatomy/brain/organ.webp" alt="Anatomical brain illustration"/><span>Explore every layer</span><i>01</i></div></section>
  <section className="market-anywhere"><div className="market-anywhere-content"><p className="market-kicker blue"><Cuboid size={16}/> LEARN FROM EVERY ANGLE</p><h2>learn whenever,<br/>wherever curiosity strikes</h2><p>Pick up a short lesson on your phone, inspect an organ in the atlas, or return to a concept that needs another look.</p><div className="market-store-row"><button><Play size={22} fill="currentColor"/><span><small>AVAILABLE ON</small>Web and mobile</span></button><button><Stethoscope size={23}/><span><small>BUILT FOR</small>Curious learners</span></button></div></div><div className="market-anywhere-art"><img src="/mimi/mascots/mimi-study.png" alt="Mimi studying anatomy"/><div><b>3D anatomy</b><span>Move · zoom · discover</span></div></div></section>
  <section className="market-plus"><div className="market-plus-art"><img src="/mimi/mascots/mimi-celebrate.png" alt="Mimi celebrating progress"/><span className="plus-star">✦</span><span className="plus-ring"/></div><div><p className="market-kicker mint"><Sparkles size={16}/> MIMI PLUS</p><h2>Make your study time go further.</h2><p>Unlock unlimited review, focused practice sessions, and a clearer picture of what to study next.</p><Button kind="white" onClick={()=>onNavigate('/signup')}>Try Mimi Plus</Button></div></section>
  <section className="market-split market-certify"><div className="market-anatomy-poster"><img src="/study/anatomy/heart/organ.webp" alt="Human heart anatomy"/><span>HEART LAB</span><i><ShieldCheck/> Evidence based</i></div><div><p className="market-kicker green"><Stethoscope size={16}/> PRACTICE WITH PURPOSE</p><h2>Get closer to clinical thinking.</h2><p>Test what a structure does, where it sits, and how it relates to the system around it. Then revisit exactly what needs attention.</p><button className="market-inline" onClick={onDemo}>Try a quick challenge <ArrowRight size={18}/></button></div></section>
  <section className="market-final"><div className="market-final-copy"><p className="market-kicker green">YOUR BODY, YOUR MAP</p><h2>Learn anatomy with Mimi.</h2><Button onClick={()=>onNavigate('/signup')}>Get started <ArrowRight size={18}/></Button></div><div className="market-final-art"><img src="/mimi/mascots/mimi-lesson-companion-clean.png" alt="Mimi holding an anatomy card"/></div></section>
  <footer className="market-footer"><div className="market-footer-grid"><div className="market-footer-intro"><Logo/><p>Playful, visual anatomy learning for people who want to understand the human body.</p><button onClick={onDemo}>Try public demo <ArrowRight size={15}/></button></div>{footerColumns.map(([heading,...links])=><div key={heading}><b>{heading}</b>{links.map(link=><a href="#top" key={link}>{link}</a>)}</div>)}</div><div className="market-footer-bottom"><span>© 2026 Mimi</span><span>Made for anatomy curiosity</span><button onClick={()=>onNavigate('/login')}>Log in</button></div></footer>
 </main>;
}
