import type {Activity,Lesson,Unit} from './mimi-lesson-types';
export type {Activity,Lesson,Unit} from './mimi-lesson-types';

const reference=['Moore, Clinically Oriented Anatomy, 9th ed.'];
const base=(id:string,prompt:string,explanation:string,learningObjective:string,concept?:string)=>({id,prompt,explanation,learningObjective,concept,difficulty:'foundation' as const,references:reference});
const mcq=(id:string,prompt:string,options:string[],answer:number,explanation:string,objective:string,concept?:string):Activity=>({...base(id,prompt,explanation,objective,concept),kind:'mcq',options,answer});
const lesson=(id:string,title:string,icon:string,activities:Activity[]):Lesson=>({id,title,icon,subtitle:'8 min · interactive',activities});

const foundationMap:Activity[]=[
 {...base('fnd-3d-brain','Rotate the brain, then type the posterior-inferior structure that coordinates balance and gait.','The cerebellum integrates sensory input to coordinate posture, balance, and voluntary movement.','Use a 3D landmark to identify a major brain structure.','Brain'),kind:'type-label',organ:'brain',target:'cerebellum',accepted:['cerebellum'],hint:'Look behind and below the cerebral hemispheres.'},
 mcq('fnd-plane','Which plane divides the body into right and left portions?',['Frontal','Sagittal','Transverse','Oblique'],1,'A sagittal plane divides the body into right and left portions.','Recognize anatomical planes.'),
 mcq('fnd-medial','The heart is ___ to the lungs.',['Lateral','Superior','Medial','Posterior'],2,'The heart lies near the midline, so it is medial to both lungs.','Use relational anatomical language.','Heart'),
 mcq('fnd-superior','Which term means closer to the head?',['Proximal','Inferior','Superior','Distal'],2,'Superior means toward the head; inferior means toward the feet.','Apply directional terminology.'),
 mcq('fnd-cavity','The heart is located within which major body cavity?',['Cranial cavity','Thoracic cavity','Abdominopelvic cavity','Vertebral canal'],1,'The heart lies in the thoracic cavity, within the mediastinum.','Associate a structure with its body cavity.','Heart'),
 mcq('fnd-prone','A patient lying face down is described as…',['Supine','Prone','Lateral','Anterior'],1,'Prone means lying face down; supine means lying face up.','Use standard patient-position terminology.'),
];

const positionMap:Activity[]=[
 {...base('fnd-femur-head','Rotate the femur, then type the rounded proximal structure that articulates with the acetabulum.','The femoral head articulates with the acetabulum to form the hip joint.','Identify a long-bone landmark in 3D.','Skeletal system'),kind:'type-label',organ:'femur',target:'head',accepted:['femoral head','head of femur','head'],hint:'Find the smooth, rounded end nearest the hip.'},
 mcq('fnd-anatomical-position','In standard anatomical position, the palms face…',['Posteriorly','Medially','Anteriorly','Inferiorly'],2,'The palms face anteriorly in standard anatomical position.','Describe the reference posture used in anatomy.'),
 mcq('fnd-proximal','The elbow is ___ to the wrist.',['Distal','Proximal','Inferior','Medial'],1,'Proximal means nearer to the trunk or point of attachment.','Apply proximal and distal terminology.'),
 mcq('fnd-joint-axis','Flexion and extension mainly occur in which anatomical plane?',['Sagittal','Frontal','Transverse','Oblique'],0,'Flexion and extension are primarily movements in the sagittal plane.','Connect planes with movement.'),
];

const directionalMap:Activity[]=[
 {...base('fnd-biceps','Rotate the upper-arm model, then type the anterior muscle that flexes the elbow.','Biceps brachii lies in the anterior arm and helps flex the elbow.','Locate an anterior muscle using a movement clue.','Muscular system'),kind:'type-label',organ:'muscle-arm',target:'biceps',accepted:['biceps','biceps brachii'],hint:'Inspect the prominent muscle on the front of the arm.'},
 mcq('fnd-anterior','The sternum is ___ to the heart.',['Posterior','Anterior','Inferior','Lateral'],1,'The sternum lies anterior to the heart.','Use anterior and posterior relationships.'),
 mcq('fnd-superficial','The skin is ___ to skeletal muscle.',['Deep','Superficial','Distal','Medial'],1,'Skin is superficial to muscle because it is closer to the body surface.','Use superficial and deep terminology.'),
 mcq('fnd-ipsilateral','The right hand and right foot are described as…',['Contralateral','Ipsilateral','Proximal','Superficial'],1,'Ipsilateral structures are on the same side of the body.','Distinguish same-side from opposite-side relationships.'),
];

const respiratoryFoundation:Activity[]=[
 {...base('fnd-trachea','Rotate the lungs, then type the central airway that divides toward both lungs.','The trachea conducts air from the larynx and divides into the main bronchi.','Identify a respiratory landmark in 3D.','Lungs'),kind:'type-label',organ:'lungs',target:'trachea',accepted:['trachea','windpipe'],hint:'Look above the branching bronchi in the midline.'},
 mcq('fnd-thoracic-cavity','The lungs are located within the…',['Cranial cavity','Thoracic cavity','Vertebral canal','Pelvic cavity'],1,'The lungs occupy the thoracic cavity on either side of the mediastinum.','Associate an organ with its body cavity.','Lungs'),
 mcq('fnd-lateral','Each lung is ___ to the heart.',['Medial','Lateral','Superior','Posterior'],1,'The lungs lie lateral to the centrally positioned heart.','Apply medial and lateral terminology.','Lungs'),
 mcq('fnd-inferior','The diaphragm is ___ to the lungs.',['Superior','Anterior','Inferior','Medial'],2,'The diaphragm forms the inferior boundary of the thoracic cavity.','Use a spatial relationship in the thorax.','Lungs'),
];

const heartChambers:Activity[]=[
 {...base('heart-lv-identify','Rotate the heart, then type the chamber with the thickest myocardium.','The left ventricle generates the pressure needed for systemic circulation, so its wall is the thickest.','Identify the left ventricle by location and function.','Heart'),kind:'type-label',organ:'heart',target:'left-ventricle',accepted:['left ventricle','lv'],hint:'It is the lower chamber that sends blood into the aorta.'},
 {...base('heart-lv-type','Type the name of the chamber that pumps oxygenated blood into the aorta.','The left ventricle ejects oxygenated blood through the aortic valve into the aorta.','Recall the systemic pumping chamber.','Heart'),kind:'type-label',organ:'heart',target:'left-ventricle',accepted:['left ventricle','lv'],hint:'It has the thickest wall and lies below the left atrium.'},
 {...base('heart-mitral-function','Inspect the highlighted valve. What does it prevent during ventricular systole?','The mitral valve closes when left-ventricular pressure exceeds left-atrial pressure, preventing regurgitation into the left atrium.','Relate mitral-valve anatomy to one-way blood flow.','Heart'),kind:'function-from-model',organ:'heart',target:'mitral',options:['Backflow into the left atrium','Blood entering the pulmonary trunk','Venous return through the vena cava','Coronary arterial supply'],answer:0},
 {...base('heart-flow-order','Build the venous-to-pulmonary flow pathway in order.','Deoxygenated blood enters the right atrium, passes the tricuspid valve into the right ventricle, then leaves through the pulmonary trunk.','Sequence right-heart blood flow.','Heart'),kind:'sequence-flow',steps:[{id:'ra',label:'Right atrium'},{id:'tv',label:'Tricuspid valve'},{id:'rv',label:'Right ventricle'},{id:'pt',label:'Pulmonary trunk'}],answer:['ra','tv','rv','pt']},
 {...base('heart-case-rv','A pulmonary embolus abruptly raises pulmonary vascular resistance. Which chamber faces the immediate increase in afterload?','The right ventricle ejects into the pulmonary circulation, so an acute rise in pulmonary resistance increases its afterload.','Apply chamber anatomy to a clinical pressure change.','Heart'),kind:'case-application',organ:'heart',target:'right-ventricle',options:['Left atrium','Left ventricle','Right atrium','Right ventricle'],answer:3},
 mcq('heart-veins','Which vessel returns oxygen-rich blood from the lungs to the heart?',['Pulmonary artery','Superior vena cava','Pulmonary veins','Aorta'],2,'Pulmonary veins return oxygenated blood to the left atrium.','Differentiate pulmonary arteries from pulmonary veins.','Heart'),
 {...base('heart-ra-identify','Rotate the model, then type the chamber that receives blood from the superior and inferior venae cavae.','The right atrium receives systemic venous return before blood crosses the tricuspid valve.','Identify the right atrium from venous inflow.','Heart'),kind:'type-label',organ:'heart',target:'right-atrium',accepted:['right atrium','ra'],hint:'It is superior to the right ventricle and receives systemic venous blood.'},
 {...base('heart-aorta-type','Type the name of the large artery that receives blood directly from the left ventricle.','The aorta begins at the left ventricle and distributes oxygenated blood to systemic circulation.','Recall the principal systemic artery.','Heart'),kind:'type-label',organ:'heart',target:'aorta',accepted:['aorta','ascending aorta'],hint:'It arches superiorly from the heart.'},
 mcq('heart-valve-count','How many cusps does a normal tricuspid valve have?',['One','Two','Three','Four'],2,'The tricuspid valve has three cusps and lies between the right atrium and right ventricle.','Differentiate the atrioventricular valves.','Heart'),
];

const heartFlow:Activity[]=[
 {...base('heart-aorta-identify','Rotate the heart, then type the great vessel that carries blood from the left ventricle to systemic circulation.','The aorta is the major systemic artery and receives blood from the left ventricle.','Identify the aorta on a 3D heart.','Heart'),kind:'type-label',organ:'heart',target:'aorta',accepted:['aorta','ascending aorta'],hint:'Look superiorly from the left ventricle.'},
 {...base('heart-atrium-type','Type the chamber that receives oxygenated blood from the pulmonary veins.','Pulmonary veins empty into the left atrium.','Recall pulmonary venous return.','Heart'),kind:'type-label',organ:'heart',target:'left-atrium',accepted:['left atrium','la'],hint:'It is superior to the left ventricle.'},
 ...heartChambers.slice(2),
];

const brainLab:Activity[]=[
 {...base('brain-cerebellum','Rotate the brain, then type the structure most associated with coordination of gait and eye movements.','The cerebellum integrates sensory input to coordinate balance and voluntary movement.','Locate the cerebellum on a 3D brain.','Brain'),kind:'type-label',organ:'brain',target:'cerebellum',accepted:['cerebellum'],hint:'Find the posterior-inferior structure.'},
 mcq('brain-vision','Which lobe is most associated with vision?',['Temporal','Parietal','Occipital','Frontal'],2,'The occipital lobe contains the primary visual cortex.','Identify functional cortical regions.','Brain'),
 {...base('brain-frontal-type','Type the lobe most associated with planning, executive control, and voluntary motor initiation.','The frontal lobe contributes to executive function and contains primary motor cortex.','Relate cortical location to function.','Brain'),kind:'type-label',organ:'brain',target:'frontal',accepted:['frontal lobe','frontal'],hint:'It lies anteriorly in the cerebral hemisphere.'},
 mcq('brain-brainstem','Which structure connects the cerebrum with the spinal cord and contains vital autonomic centers?',['Cerebellum','Brainstem','Parietal lobe','Hippocampus'],1,'The brainstem links the brain to the spinal cord and houses important respiratory and cardiovascular control centers.','Recognize the brainstem’s core role.','Brain'),
 {...base('brain-case-mca','A patient has weakness of the contralateral face and upper limb after an ischemic stroke. Which arterial territory is most likely affected?','The middle cerebral artery supplies much of the lateral cerebral hemisphere, including motor cortex regions for face and upper limb.','Connect cortical topography with a stroke presentation.','Brain'),kind:'case-application',organ:'brain',target:'frontal',options:['Anterior cerebral artery','Middle cerebral artery','Posterior cerebral artery','Basilar artery'],answer:1},
 mcq('brain-csf','Cerebrospinal fluid is produced mainly by the…',['Choroid plexus','Dura mater','Pia mater','Basal ganglia'],0,'The choroid plexus within the ventricles produces most cerebrospinal fluid.','Recognize a core source of cerebrospinal fluid.','Brain'),
 ...foundationMap.slice(1,3),
];
const lungLab:Activity[]=[
 {...base('lung-trachea','Rotate the lungs, then type the airway that conducts air toward both lungs.','The trachea divides into the main bronchi and carries air from the larynx toward the lungs.','Locate the trachea in relation to the lungs.','Lungs'),kind:'type-label',organ:'lungs',target:'trachea',accepted:['trachea','windpipe'],hint:'It is the central airway above the branching bronchi.'},
 mcq('lung-gas','Gas exchange happens primarily in the…',['Bronchi','Alveoli','Larynx','Pharynx'],1,'Alveoli provide the thin diffusion surface for oxygen and carbon dioxide.','Identify the site of gas exchange.','Lungs'),
 {...base('lung-bronchus-type','Type the branching airway that carries air from the trachea into a lung.','A main bronchus branches from the trachea and conducts air into each lung.','Name a major airway from its relationship to the trachea.','Lungs'),kind:'type-label',organ:'lungs',target:'bronchus',accepted:['bronchus','main bronchus','bronchi'],hint:'It sits immediately below the trachea at the bifurcation.'},
 mcq('lung-aspiration','An aspirated object is more likely to enter the right main bronchus because it is…',['Longer and narrower','More horizontal','Wider, shorter, and more vertical','Separated from the trachea by a valve'],2,'The right main bronchus is wider, shorter, and more vertical than the left.','Apply airway anatomy to aspiration risk.','Lungs'),
 mcq('lung-perfusion','In an upright person, which lung region normally has the greatest perfusion?',['Apex','Base','Hilum','Equal at all levels'],1,'Gravity increases pulmonary blood flow toward the lung bases in an upright person.','Apply gravity to ventilation-perfusion patterns.','Lungs'),
 {...base('lung-case-pleura','A patient develops a pneumothorax after trauma. Which space has filled with air?','A pneumothorax introduces air into the pleural cavity, disrupting the pressure relationship that keeps the lung expanded.','Apply pleural anatomy to a clinical emergency.','Lungs'),kind:'case-application',organ:'lungs',target:'left-lung',options:['Pericardial cavity','Pleural cavity','Peritoneal cavity','Mediastinum'],answer:1},
 ...foundationMap.slice(1,3),
];
const liverLab:Activity[]=[
 {...base('liver-lobe','Rotate the liver, then type its largest lobe.','The right lobe is the largest hepatic lobe.','Identify liver surface anatomy.','Liver'),kind:'type-label',organ:'liver',target:'right-lobe',accepted:['right lobe','right hepatic lobe'],hint:'It occupies most of the organ’s anatomical right side.'},
 mcq('liver-bile','Which organ produces bile?',['Liver','Pancreas','Stomach','Kidney'],0,'The liver produces bile; the gallbladder stores and concentrates it.','Identify major digestive organ functions.','Liver'),
 {...base('liver-portal-type','Type the vessel that brings nutrient-rich blood from the gastrointestinal tract to the liver.','The hepatic portal vein brings nutrient-rich venous blood from abdominal organs to the liver.','Relate portal circulation to hepatic metabolism.','Liver'),kind:'type-label',organ:'liver',target:'portal',accepted:['portal vein','hepatic portal vein'],hint:'It enters the liver at the porta hepatis.'},
 mcq('liver-detox','Which liver function best explains why orally administered drugs often undergo first-pass metabolism?',['Filtering lymph','Receiving portal venous blood','Producing insulin','Storing cerebrospinal fluid'],1,'Portal venous blood travels from the gut to the liver before reaching systemic circulation.','Apply portal circulation to drug metabolism.','Liver'),
 mcq('liver-protein','Which plasma protein is synthesized primarily by the liver and contributes substantially to oncotic pressure?',['Albumin','Insulin','Hemoglobin','Thyroxine'],0,'Albumin is made by the liver and helps maintain plasma oncotic pressure.','Connect hepatic synthesis with fluid balance.','Liver'),
 {...base('liver-case-bilirubin','Obstruction of the common bile duct most directly impairs delivery of which substance to the duodenum?','Bile travels through the biliary tree to the duodenum, where it helps emulsify dietary fats.','Apply hepatobiliary anatomy to an obstruction.','Liver'),kind:'case-application',organ:'liver',target:'portal',options:['Bile','Insulin','Cerebrospinal fluid','Surfactant'],answer:0},
 ...foundationMap.slice(1,3),
];
const skeletalLab:Activity[]=[
 {...base('skel-femur-model','Rotate the femur model, then type the rounded proximal structure that articulates with the acetabulum.','The femoral head articulates with the acetabulum to form the hip joint.','Identify the proximal femur in a 3D model.','Skeletal system'),kind:'type-label',organ:'femur',target:'head',accepted:['femoral head','head of femur','head'],hint:'Inspect the rounded end at the hip.'},
 {...base('skel-femur-function','Inspect the 3D femur. Which role best describes this bone?','The femur transfers body weight from the hip toward the knee and provides broad attachment surfaces for muscles.','Relate femoral form to locomotor function.','Skeletal system'),kind:'function-from-model',organ:'femur',target:'shaft',options:['Transmits weight between hip and knee','Protects the brain','Filters blood plasma','Produces cerebrospinal fluid'],answer:0},
 mcq('skel-cranium','Which bone protects the brain?',['Scapula','Cranium','Sternum','Femur'],1,'The cranium encloses and protects the brain.','Identify the skull vault.'),
 mcq('skel-femur','What is the longest bone in the adult human body?',['Humerus','Tibia','Femur','Radius'],2,'The femur is the longest and strongest bone in the body.','Identify a major lower-limb bone.'),
 mcq('skel-patella','The patella is commonly called the…',['Shoulder blade','Kneecap','Collarbone','Hip bone'],1,'The patella is the sesamoid bone embedded in the quadriceps tendon at the knee.','Recognize the patella.','Skeletal system'),
 mcq('skel-axial','Which structure belongs to the axial skeleton?',['Femur','Scapula','Sternum','Humerus'],2,'The sternum is part of the axial skeleton along with skull, vertebral column, and thoracic cage.','Distinguish axial from appendicular skeleton.'),
 mcq('skel-joint','What type of synovial joint is the shoulder (glenohumeral) joint?',['Hinge','Pivot','Ball-and-socket','Saddle'],2,'The glenohumeral joint is a ball-and-socket joint with wide range of motion.','Classify major synovial joints.'),
 mcq('skel-epiphyseal','In a growing long bone, the epiphyseal plate is responsible for…',['Increasing length','Increasing bone marrow volume','Forming articular cartilage','Producing synovial fluid'],0,'The epiphyseal plate is a growth plate where endochondral ossification lengthens a long bone.','Relate a long-bone region to growth.','Skeletal system'),
 mcq('skel-fracture','A fracture of the femoral neck most directly threatens blood supply to the…',['Femoral head','Patella','Tibial tuberosity','Fibular head'],0,'Femoral neck fractures can disrupt retinacular vessels to the femoral head, risking avascular necrosis.','Apply proximal femur anatomy to a clinical scenario.','Skeletal system'),
 mcq('skel-remodel','Which cell type resorbs bone during remodeling?',['Osteoblast','Osteoclast','Chondrocyte','Fibroblast'],1,'Osteoclasts resorb bone; osteoblasts lay down osteoid and mineralize new bone.','Differentiate bone-remodeling cell types.','Skeletal system'),
 ...foundationMap.slice(1,2),
];

const muscleLab:Activity[]=[
 {...base('muscle-biceps-model','Rotate the upper-arm model, then type the muscle on the anterior arm that flexes the elbow.','Biceps brachii lies in the anterior compartment and flexes the elbow; it also helps supinate the forearm.','Identify a major upper-arm muscle from action and position.','Muscular system'),kind:'type-label',organ:'muscle-arm',target:'biceps',accepted:['biceps','biceps brachii'],hint:'Look at the prominent muscle on the front of the upper arm.'},
 {...base('muscle-triceps-function','Inspect the opposing posterior upper-arm muscle. Which movement does it produce at the elbow?','Triceps brachii extends the elbow by pulling on the olecranon of the ulna.','Connect a muscle’s position with its primary action.','Muscular system'),kind:'function-from-model',organ:'muscle-arm',target:'triceps',options:['Elbow extension','Elbow flexion','Hip flexion','Wrist pronation'],answer:0},
 mcq('muscle-antagonist','During elbow flexion, biceps brachii and triceps brachii are best described as…',['Synergists','Antagonists','Ligaments','Tendons'],1,'They are antagonists: biceps flexes the elbow while triceps extends it.','Recognize opposing muscle pairs.','Muscular system'),
 mcq('muscle-diaphragm','Which muscle is the primary driver of quiet inspiration?',['Rectus abdominis','Diaphragm','Trapezius','Gluteus maximus'],1,'The diaphragm contracts and descends to increase thoracic volume during quiet inspiration.','Identify a core respiratory muscle.','Muscular system'),
 mcq('muscle-rotator-cuff','Which muscle is part of the rotator cuff?',['Biceps brachii','Supraspinatus','Pectoralis major','Latissimus dorsi'],1,'Supraspinatus, infraspinatus, teres minor, and subscapularis stabilize the glenohumeral joint.','Recognize the rotator cuff.','Muscular system'),
 {...base('muscle-case-radial','A patient cannot actively extend the elbow after a posterior arm injury. Which muscle is most likely impaired?','Triceps brachii is the primary extensor of the elbow and is innervated by the radial nerve.','Apply muscle action to a clinical deficit.','Muscular system'),kind:'case-application',organ:'muscle-arm',target:'triceps',options:['Biceps brachii','Brachialis','Triceps brachii','Pronator teres'],answer:2},
 mcq('muscle-sarcomere','Which structure is the basic contractile unit of skeletal muscle?',['Osteon','Sarcomere','Alveolus','Nephron'],1,'Sarcomeres are repeating actin-myosin units that shorten during skeletal-muscle contraction.','Relate microscopic organization to muscle contraction.','Muscular system'),
];

const named=(prefix:string,titles:string[],icon:string,activities:Activity[])=>titles.map((title,index)=>lesson(`${prefix}-${index+1}`,title,icon,activities));

export const units:Unit[]=[
 {id:'foundations',title:'Foundations',description:'Orientation, body planes, and anatomical language.',color:'#ff8669',lessons:[
 lesson('anatomy-map','Your anatomy map','✦',foundationMap),
  lesson('anatomical-position','Anatomical position','↕',positionMap),
  ...['Directional language','Planes in practice','Inside the body','Regions and quadrants','Surface landmarks','Imaging orientation','Movement vocabulary','Anatomy map lab','Foundations checkpoint'].map((title,index)=>lesson(`foundations-${index+1}`,title,'◫',[directionalMap,respiratoryFoundation,positionMap,foundationMap][index%4])),
 ]},
 {id:'skeletal',title:'Skeletal System',description:'Build your framework from skull to toes.',color:'#f4b844',lessons:named('skeletal',['Bones, first look','Bone tissue','Axial skeleton','Skull landmarks','Vertebral column','Thoracic cage','Upper limb','Hand and wrist','Pelvis','Lower limb','Joints in motion','Skeletal checkpoint'],'🦴',skeletalLab)},
 {id:'muscular',title:'Muscular System',description:'Link form, force, movement, and clinical function.',color:'#d9565b',lessons:named('muscle',['Muscle map','Upper arm actions','Rotator cuff','Forearm compartments','Hip and thigh','Leg and ankle','Diaphragm','Muscle contraction','Peripheral nerve injuries','Muscular checkpoint'],'💪',muscleLab)},
 {id:'heart',title:'Heart & Circulation',description:'Follow the route of every heartbeat.',color:'#ee6f63',lessons:[lesson('heart-chambers','Heart chambers','♥',heartChambers),lesson('heart-flow','Blood flow','↗',heartFlow),...named('heart',['External anatomy','Heart valves','Great vessels','Coronary circulation','Conduction system','Cardiac cycle','Pressure and flow','Fetal circulation','Clinical heart cases','Heart checkpoint'],'♥',heartFlow)]},
 {id:'brain',title:'Brain & Nerves',description:'Trace signals from thought to movement.',color:'#9076e8',lessons:named('brain',['Brain orientation','Brain regions','Cerebellum and balance','Brainstem','Cranial nerves','Motor pathways','Sensory pathways','Autonomic system','Neuro cases','Brain checkpoint'],'◉',brainLab)},
 {id:'respiratory',title:'Respiratory System',description:'Learn how oxygen reaches every cell.',color:'#55b9c4',lessons:named('resp',['Airway orientation','Lung lobes','Bronchial tree','Pleura','Alveoli','Gas exchange','Ventilation and perfusion','Diaphragm','Respiratory cases','Breathing checkpoint'],'☁',lungLab)},
 {id:'digestive',title:'Digestion & Metabolism',description:'Turn food into fuel.',color:'#71b65d',lessons:named('digest',['Digestive map','Stomach','Liver anatomy','Pancreas','Intestine','Portal circulation','Absorption','Metabolic roles','Digestive cases','Digestive checkpoint'],'⌇',liverLab)},
];

export const allLessons=units.flatMap(unit=>unit.lessons.map(lesson=>({...lesson,unit})));
